# AndroidX ?????? true??? AndroidX ??? release ??????
android.useAndroidX=true

# ?? AndroidX ???????? support ????? AndroidX ???
android.enableJetifier=true

# Gradle JVM ????CI ????? OOM?
org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError

# ????
org.gradle.parallel=true

# ??????
org.gradle.caching=true

# Kotlin ????
kotlin.code.style=official

